on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Elixir 1.15.x with supported OTP versions
          - elixir: '1.15.8'
            otp: '24.3'
          - elixir: '1.15.8'
            otp: '26.2'

          # Elixir 1.16.x with supported OTP versions
          - elixir: '1.16.3'
            otp: '24.3'
          - elixir: '1.16.3'
            otp: '26.2'

          # Elixir 1.17.x with supported OTP versions
          - elixir: '1.17.3'
            otp: '25.3'
          - elixir: '1.17.3'
            otp: '27.1'

          # Elixir 1.18.x with supported OTP versions (including OTP 28)
          - elixir: '1.18.4'
            otp: '25.3'
          - elixir: '1.18.4'
            otp: '28.0'
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
          version-type: 'strict'
      - run: mix deps.get
      - run: mix test
